language: java

sudo: true

before_install:
  - chmod +x mvnw

script:
  - ./.ci/unit-tests.sh
  - ./.ci/integration-tests.sh

codecov:
    token: 9bf0508f-b097-49c5-82b8-9aac3f1c458c

after_success:
  - bash <(curl -s https://codecov.io/bash)
