language: java

sudo: true

before_install:
  - chmod +x mvnw

script:
  - chmod +x ./.ci/script.sh
  - ./.ci/script.sh

env:
 global:
   - CODECOV_TOKEN=9bf0508f-b097-49c5-82b8-9aac3f1c458c

after_success:
  - bash <(curl -s https://codecov.io/bash)
