name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 17
                  check-latest: true
            - name: Add permissions
              run: chmod +x mvnw && chmod +x .ci/unit-tests.sh && chmod +x .ci/integration-tests.sh
            - name: Build Integration Tests
              run: ./.ci/integration-tests.sh
            - name: Build Unit Tests
              run: ./.ci/unit-tests.sh