name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: 17
            - name: Add permissions
              run: chmod +x mvnw && chmod +x .ci/script.sh
            - name: Build Tests
              run: ./.ci/script.sh
